name: model_repository
description: Dart package which manages the authentication domain.
publish_to: none

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  parse_server_sdk_flutter: ^7.0.0
  equatable: ^2.0.5