name: database_repository
description: Dart package which manages the authentication domain.
publish_to: none

environment:
  sdk: ">=2.16.0-0 <3.0.0"

dependencies:
  parse_server_sdk_flutter: ^3.1.0
  model_repository:
    path: ../model_repository
  flutter_dotenv: ^5.0.2