name: database_repository
description: Dart package which manages the authentication domain.
publish_to: none

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  parse_server_sdk_flutter: ^7.0.0
  model_repository:
    path: ../model_repository
  storage_repository: 
    path: ../storage_repository
  auth_repository:
    path: ../auth_repository

  flutter_dotenv: ^5.1.0
  firebase_messaging: ^14.7.5
  