name: o18_staff
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0

# firebase
  firebase_core: any
  firebase_messaging: any

# server
  parse_server_sdk_flutter: ^3.1.0

# architecture
  mobx: ^2.0.7+7
  flutter_mobx: ^2.0.6+3

# local packages
  storage_repository:
    path: packages/storage_repository
  model_repository:
    path: packages/model_repository
  database_repository:
    path: packages/database_repository
  authentication_repository:
    path: packages/authentication_repository

# keys and secrets
  flutter_dotenv: ^5.0.2

# other
  http: ^0.13.4
  table_calendar: ^3.0.2
  path_provider: ^2.0.5
  provider: ^6.0.1
  cupertino_icons: ^1.0.2
  image_picker: ^1.0.2
  formz: ^0.6.0
  equatable: ^2.0.3
  flutter_screenutil: ^5.5.3+2
  dropdown_button2: ^2.1.3
  flutter_masked_text2: ^0.9.1
  dropdown_search: ^5.0.2
  flow_builder: ^0.0.9
  validators: ^3.0.0
  url_launcher: ^6.1.7
  flutter_app_badger: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.1
  mobx_codegen: ^2.0.7+2

flutter:
  assets:
    - .env
  uses-material-design: true

