name: o18_client
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0

  # firebase
  firebase_core: ^2.23.0
  firebase_messaging: ^14.7.5

  # server
  parse_server_sdk_flutter: ^7.0.0

  # local packages
  storage_repository:
    path: packages/storage_repository
  model_repository:
    path: packages/model_repository
  database_repository:
    path: packages/database_repository
  auth_repository:
    path: packages/auth_repository

  # keys and secrets
  flutter_dotenv: ^5.1.0

  # other
  http: ^0.13.6
  table_calendar: ^3.0.9
  path_provider: ^2.1.1
  provider: ^6.1.1
  cupertino_icons: ^1.0.6
  image_picker: ^1.0.4
  formz: ^0.6.1
  equatable: ^2.0.5
  flutter_screenutil: ^5.9.0
  dropdown_button2: ^2.3.9
  flutter_masked_text2: ^0.9.1
  dropdown_search: ^5.0.6
  flow_builder: ^0.0.10
  validators: ^3.0.0
  url_launcher: ^6.2.1
  flutter_app_badger: ^1.5.0
  flutter_local_notifications: ^16.1.0
  flutter_bloc: ^8.1.3
  fl_chart: ^0.64.0
  mailto: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6

flutter:
  assets:
    - .env
    - assets/images/appIcon.png
  uses-material-design: true
