name: authentication_repository
description: Dart package which manages the authentication domain.
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  parse_server_sdk_flutter: ^3.1.0
  equatable: ^2.0.3
  cache:
    path: ../cache
  database_repository:
    path: ../database_repository
